# Generated by Django 2.1.5 on 2019-03-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
